FROM node:25-alpine AS build

RUN apk update && apk upgrade --no-cache

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG REACT_APP_USER_SERVICE_URL
ARG REACT_APP_PRODUCT_SERVICE_URL
ARG REACT_APP_CART_SERVICE_URL
ARG REACT_APP_ORDER_SERVICE_URL

ENV REACT_APP_USER_SERVICE_URL=$REACT_APP_USER_SERVICE_URL \
    REACT_APP_PRODUCT_SERVICE_URL=$REACT_APP_PRODUCT_SERVICE_URL \
    REACT_APP_CART_SERVICE_URL=$REACT_APP_CART_SERVICE_URL \
    REACT_APP_ORDER_SERVICE_URL=$REACT_APP_ORDER_SERVICE_URL

RUN npm run build


FROM nginx:1.27-alpine

RUN apk update && apk upgrade --no-cache && \
    addgroup -S appgroup && \
    adduser -S appuser -G appgroup

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/build /usr/share/nginx/html

RUN chown -R appuser:appgroup /usr/share/nginx/html && \
    chown -R appuser:appgroup /var/cache/nginx && \
    chown -R appuser:appgroup /var/log/nginx && \
    touch /run/nginx.pid && \
    chown appuser:appgroup /run/nginx.pid

USER appuser

EXPOSE 5005

ENTRYPOINT ["nginx", "-g", "daemon off;"]