sonar.projectKey=container-vuln-scanner
sonar.projectName=Container Vuln Scanner
sonar.sources=scripts,notifications
sonar.sourceEncoding=UTF-8
sonar.exclusions=reports/**,docs/**,projects/**,dashboards/**
