apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: blue-green
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: backend-external
  namespace: blue-green
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30500
  type: NodePort