apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: blue-green
  labels:
    app: frontend
    version: blue
spec:
  selector:
    app: frontend
    version: blue
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 30100
  type: NodePort