sonar.projectKey=streamingapp-assignment-hv
sonar.projectName=StreamingApp Assignment HV
sonar.sources=backend,frontend
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,screenshots/**,helm/**,docs/**
