pipeline {
    agent any

    environment {
        PATH          = "/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
        //IMAGE_NAME    = "myapp:${BUILD_NUMBER}"
        IMAGE_NAME = "e-commercestore-cart-service:latest"
        FAIL_SEVERITY = "HIGH,CRITICAL"
    }

    stages {
        stage('Build Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Show Vulnerabilities') {
            steps {
                // exit-code 0 → never fails; full table in Console Output
                sh 'trivy image --exit-code 0 --severity $FAIL_SEVERITY $IMAGE_NAME'
            }
        }

        stage('Save Reports') {
            steps {
                sh 'trivy image --format json --output scan-report.json $IMAGE_NAME'
                sh 'python3 scripts/generate_report.py scan-report.json scan-report.html'
                archiveArtifacts artifacts: 'scan-report.json, scan-report.html'
            }
        }

        stage('Security Gate') {
            steps {
                sh 'trivy image --exit-code 1 --severity $FAIL_SEVERITY --ignore-unfixed $IMAGE_NAME'
            }
        }

        stage('Code Quality (SonarQube)') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    withSonarQubeEnv('sonarqube-server') {   // name must match Manage Jenkins → System → SonarQube servers
                        sh 'sonar-scanner -Dsonar.host.url=https://eclair-account-chest.ngrok-free.dev -Dsonar.token=$SONAR_TOKEN'
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Push to Registry') {
            steps {
                echo '✅ Scan + quality gate passed — image is safe.'
                // sh 'docker tag $IMAGE_NAME your-registry/myapp:${BUILD_NUMBER}'
                // sh 'docker push your-registry/myapp:${BUILD_NUMBER}'
            }
        }
    }

    post {
        failure {
            echo '🚨 Build blocked: vulnerabilities or quality gate failure!'
        }
        always {
            archiveArtifacts artifacts: 'scan-report.*', allowEmptyArchive: true
        }
    }
}