image:
  registry: 251478238405.dkr.ecr.us-east-1.amazonaws.com
  tag: v1

env:
  jwtSecret: "9584bab99c7446823d4ffe263f3c94454de72e68eda16baf"
  clientUrls: "http://a2ed5a67cfacb4d8097531e8bcf7e050-1200332828.us-east-1.elb.amazonaws.com"
  streamingPublicUrl: "http://a279ed5848615483bb910f00a1e41479-1064057686.us-east-1.elb.amazonaws.com:3002"
  awsRegion: "us-west-2"
  s3Bucket: "streamingappbucketb15"
  awsAccessKeyId: ""                        # IAM user key with S3 access (for video upload/playback)
  awsSecretAccessKey: ""

mongo:
  uri: "mongodb://mongo:27017/streamingapp"

services:
  auth:      { repo: streamingapp/auth,      port: 3001, replicas: 1, serviceType: LoadBalancer }
  streaming: { repo: streamingapp/streaming, port: 3002, replicas: 1, serviceType: LoadBalancer }
  admin:     { repo: streamingapp/admin,     port: 3003, replicas: 1, serviceType: LoadBalancer }
  chat:      { repo: streamingapp/chat,      port: 3004, replicas: 1, serviceType: LoadBalancer }

frontend:
  repo: streamingapp/frontend
  replicas: 1