sonar.projectKey=blue-green-deployment
sonar.projectName=Blue-Green Deployment
sonar.sources=backend,frontend-blue,frontend-green
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,screenshots/**,k8s/**
